apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-info-manager-deployment
  namespace: default
  labels:
    app: student-info-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-info-manager
  template:
    metadata:
      labels:
        app: student-info-manager
    spec:
      containers:
        - name: student-info-manager
          image: mayberz/student-info-manager:1.0
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:27017/${DB_NAME}?authSource=${DB_NAME}"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: db.host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: db.name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: mongo-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets
                  key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: student-management-app-service
spec:
  selector:
    app: student-info-manager
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
